import "./globals.css";
import { Nata_Sans } from "next/font/google";
import Header from "@/components/comman/Header";
import Footer from "@/components/comman/Footer";

const nata = Nata_Sans({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: "normal",
  display: "swap",
  variable: "--font-nata",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="md:text-[1vw]">
      <body className={`${nata.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
